#!/usr/bin/env python3
"""
gen_emmett_header.py -- bake emmett_panel_data.json into a PROGMEM C header.

The ESP32 sketch lives in register_esp32/ and cannot read the JSON off the Pi
at runtime, so we compile the map into register_esp32/emmett_data.h. The
firmware's drawEmmett() reads only from this header -- it is the single source
of map geometry on the device, exactly mirroring the EMMETT object the browser
mock (register_panel.py) injects into the page.

Packing strategy (keeps it small + exact):
  * water:    1-bit-per-pixel bitmap, W*H bits -> ceil(W*H/8) bytes.
              Same set drawEmmett iterates; coast is derived on-device by the
              4-neighbour test, identical to the JS.
  * lake_of:  parallel array, one byte per WATER pixel (in water-iteration
              order), holding a lake id indexing E_LAKE_NAMES. Non-water pixels
              are never queried, so we only store labels for water. eLakeAt()
              does the same expanding-ring nearest-water search as the mock.
  * ports/offsets/icons/home_icons/proj: compact structs + flat arrays.

Run on the Pi from the repo root:
    .venv/bin/python3 gen_emmett_header.py
    #  -> wrote register_esp32/emmett_data.h  (water=NNN px, ... bytes)

Then rebuild/flash register_esp32/register_esp32.ino.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.environ.get("EMMETT_JSON", os.path.join(HERE, "emmett_panel_data.json"))
OUT = os.environ.get("EMMETT_HEADER",
                     os.path.join(HERE, "register_esp32", "emmett_data.h"))


def hex_to_565(h):
    """'#rrggbb' -> uint16 RGB565 (what the panel/Protomatter wants)."""
    h = h.lstrip("#")
    r = int(h[0:2], 16); g = int(h[2:4], 16); b = int(h[4:6], 16)
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def c_ident(s):
    return "".join(ch if ch.isalnum() else "_" for ch in s).upper()


def main():
    try:
        D = json.load(open(SRC))
    except FileNotFoundError:
        sys.exit(f"ERROR: {SRC} not found. Run from the repo root, or set "
                 f"EMMETT_JSON=path.")

    W, H = D["w"], D["h"]
    proj = D["proj"]
    water = [tuple(p) for p in D["water"]]
    lake_of = D.get("lake_of", {})           # "x,y" -> "LAKE"
    offsets = D["offsets"]                    # key -> {off:[ox,oy], ll:[lon,lat]}
    icons = D["icons"]                        # key -> [[dx,dy,"#hex"],...]
    ports = D["ports"]                        # key -> {ll:[lat,lon], kw:[...]}
    home_icons = D["home_icons"]              # [key,...]
    home = D.get("home", {})

    # --- water bitmap (1bpp, row-major, bit0 = first pixel of byte) ----------
    nbits = W * H
    nbytes = (nbits + 7) // 8
    bitmap = bytearray(nbytes)
    water_set = set(water)
    for (x, y) in water:
        idx = y * W + x
        bitmap[idx >> 3] |= (1 << (idx & 7))

    # --- lake ids, one byte per water pixel, in a STABLE iteration order -----
    # Order = sorted by (y, x) so the device can reproduce the same index by
    # walking the bitmap in row-major order. (The JS used insertion order of
    # the water array; we instead define the canonical order as row-major so
    # the on-device nearest-water search and label lookup agree without
    # shipping the original array order.)
    water_sorted = sorted(water, key=lambda p: (p[1], p[0]))
    lake_names = []                            # id 0 reserved for '?'
    lake_id = {"?": 0}
    lake_names.append("?")

    def name_id(nm):
        if nm not in lake_id:
            lake_id[nm] = len(lake_names)
            lake_names.append(nm)
        return lake_id[nm]

    lake_bytes = bytearray(len(water_sorted))
    for i, (x, y) in enumerate(water_sorted):
        nm = lake_of.get(f"{x},{y}", "?")
        lake_bytes[i] = name_id(nm)
    if len(lake_names) > 256:
        sys.exit(f"ERROR: {len(lake_names)} lake labels > 255; widen lake id.")

    # --- emit ----------------------------------------------------------------
    L = []
    w = L.append
    w("// AUTO-GENERATED by gen_emmett_header.py -- do not edit by hand.")
    w("// Source: emmett_panel_data.json  (Where's-Emmett Great Lakes map)")
    w("#pragma once")
    w("#include <Arduino.h>")
    w("")
    w(f"#define E_W {W}")
    w(f"#define E_H {H}")
    w(f"static const float E_LON_MIN = {proj['lon_min']:.6f}f;")
    w(f"static const float E_LON_MAX = {proj['lon_max']:.6f}f;")
    w(f"static const float E_LAT_MIN = {proj['lat_min']:.6f}f;")
    w(f"static const float E_LAT_MAX = {proj['lat_max']:.6f}f;")
    w("")

    # water bitmap
    w(f"// 1bpp water mask, row-major, {len(water)} water px")
    w(f"static const uint8_t E_WATER_BITS[{nbytes}] PROGMEM = {{")
    for i in range(0, nbytes, 16):
        w("  " + ",".join(f"0x{b:02x}" for b in bitmap[i:i+16]) + ",")
    w("};")
    w("")

    # lake labels
    w(f"#define E_NUM_LAKES {len(lake_names)}")
    w("static const char* const E_LAKE_NAMES[E_NUM_LAKES] = {")
    for nm in lake_names:
        w(f'  "{nm}",')
    w("};")
    w(f"// one lake id per water px, row-major (sorted y,x) -- {len(lake_bytes)} entries")
    w(f"static const uint8_t E_LAKE_ID[{len(lake_bytes)}] PROGMEM = {{")
    for i in range(0, len(lake_bytes), 24):
        w("  " + ",".join(str(b) for b in lake_bytes[i:i+24]) + ",")
    w("};")
    w("")

    # markers: unify offsets/icons/ports/home into one indexed table.
    # Every drawable key has an entry; fields default to absent.
    keys = list(offsets.keys())
    # ensure deterministic, mock-matching order: offsets dict order
    w("struct ECell { int8_t dx, dy; uint16_t col; };")
    w("struct EMarker {")
    w("  const char* key;")
    w("  float lon, lat;       // ll for projection (note: lon,lat)")
    w("  int8_t ox, oy;        // icon draw offset from its map dot")
    w("  const ECell* cells;   // icon silhouette, or nullptr")
    w("  uint16_t nCells;")
    w("  bool isHome;          // drawn always")
    w("  uint8_t nKw; const char* const* kw;  // destination keywords (ports)")
    w("};")
    w("")

    # icon cell arrays
    for key in keys:
        cells = icons.get(key)
        if not cells:
            continue
        cid = c_ident(key)
        w(f"static const ECell E_CELLS_{cid}[{len(cells)}] PROGMEM = {{")
        row = []
        for c in cells:
            dx, dy, col = c[0], c[1], hex_to_565(c[2])
            row.append(f"{{{dx},{dy},0x{col:04x}}}")
            if len(row) == 6:
                w("  " + ",".join(row) + ",")
                row = []
        if row:
            w("  " + ",".join(row) + ",")
        w("};")
    w("")

    # keyword arrays (ports only)
    # ports use {ll:[lat,lon]}; offsets use {ll:[lon,lat]} -- we take ll from
    # offsets for projection (lon,lat) and kw from ports.
    for key in keys:
        p = ports.get(key)
        if not p or not p.get("kw"):
            continue
        cid = c_ident(key)
        for j, kw in enumerate(p["kw"]):
            w(f'static const char E_KW_{cid}_{j}[] PROGMEM = "{kw}";')
        arr = ",".join(f"E_KW_{cid}_{j}" for j in range(len(p["kw"])))
        w(f"static const char* const E_KW_{cid}[] PROGMEM = {{{arr}}};")
    w("")

    home_set = set(home_icons)
    w(f"#define E_NUM_MARKERS {len(keys)}")
    w("static const EMarker E_MARKERS[E_NUM_MARKERS] = {")
    for key in keys:
        off = offsets[key]
        lon, lat = off["ll"][0], off["ll"][1]
        ox, oy = off["off"][0], off["off"][1]
        cid = c_ident(key)
        cells = icons.get(key)
        cells_ref = f"E_CELLS_{cid}" if cells else "nullptr"
        ncells = len(cells) if cells else 0
        is_home = "true" if key in home_set else "false"
        p = ports.get(key)
        if p and p.get("kw"):
            nkw = len(p["kw"]); kw_ref = f"E_KW_{cid}"
        else:
            nkw = 0; kw_ref = "nullptr"
        w(f'  {{"{key}",{lon:.4f}f,{lat:.4f}f,{ox},{oy},'
          f'{cells_ref},{ncells},{is_home},{nkw},{kw_ref}}},')
    w("};")
    w("")

    # home reference point (Traverse City) for distance readout
    if home:
        w(f'static const char* E_HOME_NAME = "{home.get("name","HOME")}";')
        w(f"static const float E_HOME_LAT = {home.get('lat',0.0):.4f}f;")
        w(f"static const float E_HOME_LON = {home.get('lon',0.0):.4f}f;")
    w("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(L) + "\n")

    approx = nbytes + len(lake_bytes) + sum(
        len(icons.get(k, [])) * 4 for k in keys)
    print(f"wrote {OUT}")
    print(f"  water={len(water)} px  bitmap={nbytes} B  "
          f"lake_id={len(lake_bytes)} B  lakes={len(lake_names)}  "
          f"markers={len(keys)}")
    print(f"  approx PROGMEM for map data ~= {approx} bytes "
          f"(+ strings/structs)")


if __name__ == "__main__":
    main()
