#!/usr/bin/env python3
"""
make_sprites.py  --  Design 16x16 stack-livery sprites and export them.

Each sprite is a stylised ship's funnel (smokestack) showing the operator's
characteristic color bands / emblem, reduced to 16x16 so it reads on a HUB75
panel. This is the funnel equivalent of FlightWall's airline logos.

Outputs:
  - sprites_preview.png   (visual check, scaled up)
  - ship_sprites.h        (RGB565 arrays for the ESP32 firmware)

Run:
    pip install pillow
    python3 make_sprites.py
"""

from PIL import Image, ImageDraw

S = 16  # sprite edge

# Palette helpers (RGB tuples).
RED    = (200, 30, 30)
DKRED  = (150, 20, 20)
WHITE  = (235, 235, 235)
BLACK  = (20, 20, 20)
YELLOW = (235, 195, 40)
GREEN  = (30, 150, 70)
BLUE   = (40, 90, 180)
GREY   = (110, 110, 110)
ORANGE = (225, 120, 30)
BG     = (0, 0, 0)        # transparent-ish; rendered as black on the panel


def base_funnel(draw, body):
    """Draw a generic funnel silhouette filled with `body`, return it."""
    # A funnel: slightly tapered column, rows 2..15, cols 4..11.
    draw.rectangle([4, 2, 11, 15], fill=body)
    # little cap lip
    draw.rectangle([3, 2, 12, 3], fill=body)


def spr_csl():
    """Canada Steamship Lines: red funnel, white band, black top."""
    img = Image.new("RGB", (S, S), BG)
    d = ImageDraw.Draw(img)
    base_funnel(d, RED)
    d.rectangle([4, 7, 11, 9], fill=WHITE)     # white band
    d.rectangle([3, 2, 12, 3], fill=BLACK)     # black cap
    return img


def spr_algoma():
    """Algoma Central: dark red funnel with white 'A' suggestion."""
    img = Image.new("RGB", (S, S), BG)
    d = ImageDraw.Draw(img)
    base_funnel(d, DKRED)
    # white 'A' chevron
    d.line([(7, 12), (5, 6)], fill=WHITE)
    d.line([(8, 12), (10, 6)], fill=WHITE)
    d.line([(6, 9), (9, 9)], fill=WHITE)
    d.rectangle([3, 2, 12, 3], fill=BLACK)
    return img


def spr_fednav():
    """Fednav: white funnel, blue band, red top (salty look)."""
    img = Image.new("RGB", (S, S), BG)
    d = ImageDraw.Draw(img)
    base_funnel(d, WHITE)
    d.rectangle([4, 6, 11, 8], fill=BLUE)
    d.rectangle([3, 2, 12, 4], fill=RED)
    return img


def spr_lowerlakes():
    """Lower Lakes Towing: green funnel, white band."""
    img = Image.new("RGB", (S, S), BG)
    d = ImageDraw.Draw(img)
    base_funnel(d, GREEN)
    d.rectangle([4, 8, 11, 10], fill=WHITE)
    return img


def spr_asc():
    """American Steamship Co: silver/grey funnel, blue top."""
    img = Image.new("RGB", (S, S), BG)
    d = ImageDraw.Draw(img)
    base_funnel(d, GREY)
    d.rectangle([3, 2, 12, 5], fill=BLUE)
    return img


def spr_interlake():
    """Interlake Steamship: orange funnel, black band."""
    img = Image.new("RGB", (S, S), BG)
    d = ImageDraw.Draw(img)
    base_funnel(d, ORANGE)
    d.rectangle([4, 8, 11, 9], fill=BLACK)
    return img


def spr_oglebay():
    """Oglebay Norton / KK Integrated: red funnel, yellow band."""
    img = Image.new("RGB", (S, S), BG)
    d = ImageDraw.Draw(img)
    base_funnel(d, RED)
    d.rectangle([4, 8, 11, 9], fill=YELLOW)
    return img


def spr_unknown():
    """Generic grey funnel for unidentified operators."""
    img = Image.new("RGB", (S, S), BG)
    d = ImageDraw.Draw(img)
    base_funnel(d, GREY)
    d.rectangle([4, 7, 11, 8], fill=(70, 70, 70))
    return img


SPRITES = {
    "CSL":        spr_csl(),
    "ALGOMA":     spr_algoma(),
    "FEDNAV":     spr_fednav(),
    "LOWERLAKES": spr_lowerlakes(),
    "ASC":        spr_asc(),
    "INTERLAKE":  spr_interlake(),
    "OGLEBAY":    spr_oglebay(),
    "UNKNOWN":    spr_unknown(),
}


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def export_preview(scale=12):
    keys = list(SPRITES.keys())
    cols = len(keys)
    pad = 4
    label_h = 0
    canvas = Image.new("RGB", (cols * (S * scale + pad) + pad,
                               S * scale + 2 * pad), (30, 30, 30))
    for i, k in enumerate(keys):
        big = SPRITES[k].resize((S * scale, S * scale), Image.NEAREST)
        x = pad + i * (S * scale + pad)
        canvas.paste(big, (x, pad))
    canvas.save("sprites_preview.png")
    print("wrote sprites_preview.png")


def export_header():
    lines = []
    lines.append("// ship_sprites.h  --  auto-generated by make_sprites.py")
    lines.append("// 16x16 RGB565 stack-livery sprites for the ESP32 firmware.")
    lines.append("#pragma once")
    lines.append("#include <Arduino.h>")
    lines.append(f"#define SPRITE_SIZE {S}")
    lines.append("")
    keys = list(SPRITES.keys())
    for k in keys:
        img = SPRITES[k].load()
        vals = []
        for y in range(S):
            for x in range(S):
                r, g, b = SPRITES[k].getpixel((x, y))
                vals.append(f"0x{rgb565(r,g,b):04X}")
        body = ", ".join(vals)
        lines.append(f"const uint16_t SPR_{k}[{S*S}] PROGMEM = {{ {body} }};")
    lines.append("")
    # Lookup table by key string.
    lines.append("struct SpriteEntry { const char* key; const uint16_t* data; };")
    entries = ", ".join(f'{{"{k}", SPR_{k}}}' for k in keys)
    lines.append(f"const SpriteEntry SPRITE_TABLE[] = {{ {entries} }};")
    lines.append(f"const int SPRITE_COUNT = {len(keys)};")
    lines.append("")
    lines.append("inline const uint16_t* spriteForKey(const char* key) {")
    lines.append("  for (int i = 0; i < SPRITE_COUNT; i++) {")
    lines.append("    if (strcmp(SPRITE_TABLE[i].key, key) == 0) return SPRITE_TABLE[i].data;")
    lines.append("  }")
    lines.append("  return SPRITE_TABLE[SPRITE_COUNT - 1].data; // UNKNOWN fallback")
    lines.append("}")
    with open("ship_sprites.h", "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote ship_sprites.h")


if __name__ == "__main__":
    export_preview()
    export_header()
