/*
 * shipwall_esp32.ino  --  St. Lawrence Ship Wall display firmware (128x64)
 *
 * Hardware (recommended build):
 *   - Adafruit MatrixPortal S3  (ESP32-S3 + HUB75 connector + level shifter
 *     + PSRAM, all on one board) -- plug the panel ribbon straight in.
 *   - 2x 64x64 HUB75E panels chained = 128x64 logical surface.
 *   - 5V / 8A power supply for the panels (NEVER power them from the board).
 *
 *   Also works on a plain ESP32 / ESP32-Trinity; see PIN CONFIG below.
 *
 * Libraries (Arduino Library Manager):
 *   - ESP32-HUB75-MatrixPanel-DMA  (by mrcodetastic)
 *   - ArduinoJson                  (by Benoit Blanchon)
 *
 * Behaviour:
 *   - Connects to 2.4 GHz WiFi, runs an HTTP server.
 *   - The Pi POSTs a JSON frame to /frame every ~10s carrying vessels,
 *     a sun-based brightness target, and a Seaway-closed flag.
 *   - ADAPTIVE LAYOUT: 1 vessel -> one large card; 2+ -> two-vessel split,
 *     cycling pairs. Brightness obeys the Pi. Idle/closed/waiting screens
 *     cover every other state so the panel is never blank or stale.
 */

#include <WiFi.h>
#include <WebServer.h>
#include <ArduinoJson.h>
#include <ESP32-HUB75-MatrixPanel-DMA.h>
#include "ship_sprites.h"   // generated by make_sprites.py (any SPRITE_SIZE)

// ---- User configuration -----------------------------------------------------
const char* WIFI_SSID = "YOUR_2.4GHz_SSID";
const char* WIFI_PASS = "YOUR_WIFI_PASSWORD";

#define PANEL_W   64        // width of one panel
#define PANEL_H   64        // height of one panel  (64 -> 1/32 scan, needs E)
#define PANEL_N   2         // panels chained -> 128x64 total

const uint32_t PAIR_DWELL_MS = 6000;   // time each vessel/pair stays on screen
const uint32_t DATA_TIMEOUT_MS = 60000;// no frame for this long -> "waiting"

// ---- PIN CONFIG -------------------------------------------------------------
// MatrixPortal S3: leave USE_DEFAULT_PINS = true; the library knows the board.
// Plain ESP32 (classic) with hand-wiring: set false and use the block below.
#define USE_DEFAULT_PINS true

// ---- Globals ----------------------------------------------------------------
MatrixPanel_I2S_DMA* dma = nullptr;
WebServer server(80);

struct Vessel {
  String name;
  String op;          // operator key -> sprite lookup
  String type;
  String dest;
  float  sog;
  int    cog;
  float  drft;
  bool   hasDrft;
};
const int MAX_V = 5;
Vessel vessels[MAX_V];
int   vesselCount = 0;
int   pairIndex   = 0;        // which vessel (or pair) is showing
uint32_t lastSwap = 0;
uint32_t lastFrameMs = 0;     // when we last heard from the Pi
bool  seawayClosed = false;
uint8_t targetBright = 128;

uint16_t C_NAME, C_LABEL, C_VALUE, C_DIM, C_ACCENT;

int W, H;   // logical width/height, filled in setup

// ---- Drawing helpers --------------------------------------------------------
void drawCentered(const char* text, int y, uint16_t color) {
  int16_t x1, y1; uint16_t w, h;
  dma->setTextSize(1);
  dma->getTextBounds(text, 0, 0, &x1, &y1, &w, &h);
  dma->setTextColor(color);
  dma->setCursor((W - w) / 2, y);
  dma->print(text);
}

// Blit a SPRITE_SIZE x SPRITE_SIZE sprite at (ox,oy); black = transparent.
void drawSprite(const uint16_t* spr, int ox, int oy) {
  for (int y = 0; y < SPRITE_SIZE; y++) {
    for (int x = 0; x < SPRITE_SIZE; x++) {
      uint16_t c = pgm_read_word(&spr[y * SPRITE_SIZE + x]);
      if (c != 0x0000) dma->drawPixel(ox + x, oy + y, c);
    }
  }
}

const uint16_t* spriteFor(const Vessel& v) {
  char opbuf[16];
  v.op.toCharArray(opbuf, sizeof(opbuf));
  return spriteForKey(opbuf);
}

// Draw one vessel within a band whose top is `top` and height is `bandH`.
// `big` selects the spacious single-vessel layout vs. the compact split row.
void drawVesselBand(const Vessel& v, int top, int bandH, bool big) {
  dma->setTextSize(1);
  const int sprX = 1;                       // funnel on the LEFT edge
  const int sprY = top + (bandH - SPRITE_SIZE) / 2;
  const int tx = SPRITE_SIZE + 3;           // text starts after the sprite

  // Name.
  dma->setTextColor(C_NAME);
  dma->setCursor(tx, top + 1);
  dma->print(v.name);

  if (big) {
    // Spacious: type+speed, course, draught, destination on separate rows.
    dma->setCursor(tx, top + 16);
    dma->setTextColor(C_LABEL); dma->print(v.type);
    dma->setTextColor(C_VALUE); dma->print(" "); dma->print(v.sog, 1);
    dma->setTextColor(C_DIM);   dma->print("kt");

    dma->setCursor(tx, top + 28);
    dma->setTextColor(C_LABEL); dma->print("CRS ");
    dma->setTextColor(C_VALUE); dma->print(v.cog);
    dma->setTextColor(C_DIM);   dma->print((char)247);

    if (v.hasDrft) {
      dma->setCursor(tx, top + 40);
      dma->setTextColor(C_LABEL); dma->print("DRAFT ");
      dma->setTextColor(C_VALUE); dma->print(v.drft, 1);
      dma->setTextColor(C_DIM);   dma->print("m");
    }
    if (v.dest.length() > 0) {
      dma->setCursor(tx, top + 52);
      dma->setTextColor(C_DIM);   dma->print(">");
      dma->setTextColor(C_VALUE); dma->print(v.dest);
    }
  } else {
    // Compact: two info rows only.
    dma->setCursor(tx, top + 11);
    dma->setTextColor(C_LABEL); dma->print(v.type);
    dma->setTextColor(C_VALUE); dma->print(" "); dma->print(v.sog, 1);
    dma->setTextColor(C_DIM);   dma->print("kt");

    dma->setCursor(tx, top + 21);
    dma->setTextColor(C_LABEL); dma->print("CRS ");
    dma->setTextColor(C_VALUE); dma->print(v.cog);
    dma->setTextColor(C_DIM);   dma->print((char)247);
    if (v.hasDrft) {
      dma->setTextColor(C_DIM); dma->print(" ");
      dma->setTextColor(C_VALUE); dma->print(v.drft, 1);
      dma->setTextColor(C_DIM); dma->print("m");
    }
  }

  drawSprite(spriteFor(v), sprX, sprY);
}

// ---- Screen states ----------------------------------------------------------
void screenSplash() {
  dma->fillScreen(0);
  drawCentered("ST LAWRENCE", H / 2 - 12, C_ACCENT);
  drawCentered("SHIP WALL", H / 2 - 2, C_NAME);
}

void screenStatus(const char* l1, const char* l2) {
  dma->fillScreen(0);
  drawCentered(l1, H / 2 - 8, C_ACCENT);
  if (l2) drawCentered(l2, H / 2 + 4, C_DIM);
}

void screenClosed() {
  dma->fillScreen(0);
  drawCentered("SEAWAY", H / 2 - 16, C_ACCENT);
  drawCentered("CLOSED", H / 2 - 4, C_NAME);
  drawCentered("reopens March", H / 2 + 10, C_DIM);
}

// Decide what to render this tick.
void render() {
  uint32_t now = millis();

  // 1) Lost contact with the Pi?
  if (lastFrameMs != 0 && now - lastFrameMs > DATA_TIMEOUT_MS) {
    screenStatus("WAITING", "for data");
    return;
  }
  // 2) Winter closure.
  if (seawayClosed && vesselCount == 0) {
    screenClosed();
    return;
  }
  // 3) Open season, but nothing on the water right now.
  if (vesselCount == 0) {
    screenStatus("ST LAWRENCE", "no vessels");
    return;
  }

  // 4) Adaptive vessel display.
  dma->fillScreen(0);
  if (vesselCount == 1) {
    drawVesselBand(vessels[0], 0, H, true);          // one big card
  } else {
    // Two-vessel split; cycle pairs if more than 2 present.
    int first = pairIndex;
    int second = (pairIndex + 1) % vesselCount;
    drawVesselBand(vessels[first], 0, H / 2, false);
    // hairline divider
    for (int x = 0; x < W; x += 2) dma->drawPixel(x, H / 2, C_DIM);
    drawVesselBand(vessels[second], H / 2 + 1, H / 2 - 1, false);
  }
}

// ---- HTTP handler -----------------------------------------------------------
void handleFrame() {
  if (server.method() != HTTP_POST) { server.send(405, "text/plain", "POST only"); return; }
  String body = server.arg("plain");
  StaticJsonDocument<3072> doc;
  if (deserializeJson(doc, body)) { server.send(400, "text/plain", "bad json"); return; }

  targetBright = (uint8_t)(int)(doc["bright"] | 128);
  seawayClosed = doc["closed"] | false;
  dma->setBrightness8(targetBright);

  JsonArray arr = doc["vessels"].as<JsonArray>();
  vesselCount = 0;
  for (JsonObject o : arr) {
    if (vesselCount >= MAX_V) break;
    Vessel& v = vessels[vesselCount];
    v.name = String((const char*)(o["name"] | "?"));
    v.op   = String((const char*)(o["op"]   | "UNKNOWN"));
    v.type = String((const char*)(o["type"] | "VSL"));
    v.dest = String((const char*)(o["dest"] | ""));
    v.sog  = o["sog"] | 0.0;
    v.cog  = o["cog"] | 0;
    if (o["drft"].isNull()) { v.hasDrft = false; v.drft = 0; }
    else { v.hasDrft = true; v.drft = o["drft"] | 0.0; }
    vesselCount++;
  }
  if (pairIndex >= vesselCount) pairIndex = 0;
  lastFrameMs = millis();
  lastSwap = 0;               // force immediate redraw
  server.send(200, "text/plain", "ok");
}

// ---- Setup / loop -----------------------------------------------------------
void setup() {
  Serial.begin(115200);

  HUB75_I2S_CFG mxconfig(PANEL_W, PANEL_H, PANEL_N);
#if !USE_DEFAULT_PINS
  // Classic ESP32 hand-wiring (matches the wiring diagram):
  mxconfig.gpio.r1=25; mxconfig.gpio.g1=26; mxconfig.gpio.b1=27;
  mxconfig.gpio.r2=14; mxconfig.gpio.g2=12; mxconfig.gpio.b2=13;
  mxconfig.gpio.a=23;  mxconfig.gpio.b=19;  mxconfig.gpio.c=5;
  mxconfig.gpio.d=17;  mxconfig.gpio.e=18;
  mxconfig.gpio.clk=16; mxconfig.gpio.lat=4; mxconfig.gpio.oe=15;
#endif
  mxconfig.clkphase = false;
  dma = new MatrixPanel_I2S_DMA(mxconfig);
  dma->begin();
  dma->setBrightness8(targetBright);
  dma->clearScreen();

  W = dma->width();
  H = dma->height();

  C_NAME   = dma->color565(255, 200,  40);
  C_LABEL  = dma->color565( 90, 140, 255);
  C_VALUE  = dma->color565(230, 230, 230);
  C_DIM    = dma->color565(110, 110, 110);
  C_ACCENT = dma->color565( 60, 220, 120);

  screenSplash();

  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  while (WiFi.status() != WL_CONNECTED) { delay(400); Serial.print("."); }
  Serial.println();
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

  server.on("/frame", handleFrame);
  server.begin();

  screenStatus("READY", WiFi.localIP().toString().c_str());
}

void loop() {
  server.handleClient();

  uint32_t now = millis();
  bool needRedraw = (lastSwap == 0);

  // Advance the pair cycle only when showing 2+ vessels.
  if (vesselCount > 2 && now - lastSwap >= PAIR_DWELL_MS) {
    pairIndex = (pairIndex + 2) % vesselCount;
    needRedraw = true;
  } else if (now - lastSwap >= PAIR_DWELL_MS) {
    needRedraw = true;   // periodic refresh for status screens / timeout check
  }

  if (needRedraw) {
    render();
    lastSwap = now;
  }
}
